source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.3'

# Use sqlite3 as the database for Active Record
# gem 'sqlite3'
gem "mysql2"

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

# TULOS

gem 'will_paginate', '~> 3.0' # https://github.com/mislav/will_paginate
gem 'will_paginate-bootstrap'

gem 'active_model_serializers' # https://github.com/rails-api/active_model_serializers

gem 'acts-as-taggable-on'

# Auth
gem 'devise' # https://github.com/plataformatec/devise

# Server
gem 'puma' # https://github.com/puma/puma

# Simple Form
gem 'simple_form' # https://github.com/plataformatec/simple_form

# Bootstrap 3
gem 'bootstrap-sass', '~> 3.1.1'

# Ember js
#gem 'ember-rails' # https://github.com/emberjs/ember-rails
#gem 'ember-source', '1.4.0' # or the version you need

# RSpec
gem 'rspec-rails' # https://github.com/rspec/rspec-rails

gem 'factory_girl' # https://github.com/thoughtbot/factory_girl
